module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.+(ts|tsx|js)', '**/*.(test|spec).+(ts|tsx|js)'],
  transform: {
    '^.+\\.(ts|tsx)$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: 'tsconfig.test.json',
      },
    ],
  },
  moduleNameMapper: {
    '^@urbanova/types$': '<rootDir>/../types/src',
    '^@urbanova/types/(.*)$': '<rootDir>/../types/src/$1',
    '^@urbanova/agents$': '<rootDir>/src',
    '^@urbanova/agents/(.*)$': '<rootDir>/src/$1',
    '^@urbanova/data$': '<rootDir>/../data/src',
    '^@urbanova/data/(.*)$': '<rootDir>/../data/src/$1',
    '^@urbanova/pdf$': '<rootDir>/../pdf/src',
    '^@urbanova/pdf/(.*)$': '<rootDir>/../pdf/src/$1',
    '^@urbanova/infra$': '<rootDir>/../infra/src',
    '^@urbanova/infra/(.*)$': '<rootDir>/../infra/src/$1',
  },
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testTimeout: 10000,
  verbose: true,
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/*.test.{ts,tsx}',
    '!src/**/*.spec.{ts,tsx}',
    '!src/**/__tests__/**',
    '!src/**/__mocks__/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transformIgnorePatterns: ['node_modules/(?!(uuid|@google-cloud|firebase-admin|jsonwebtoken)/)'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/coverage/'],
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
};
